spring:
  application:
    name: Order-Item-Client

server:
  port: 8091
  
eureka:
  client:
    service-url.default-zone: http://localhost:8761/eureka

management:
  endpoints:
      web:
       exposure:
         include: hystrix.stream
       base-path: /

info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: Item-Service
       
logging:
   level:
     ROOT: 
     org.springframework.web: INFO
     org.hibernate: ERROR
   file: /logs/orders/orderclient.log